FROM nginx:latest

COPY ./conf.d/default.conf.template /etc/nginx/conf.d/default.conf.template
COPY entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
