ARG NODE_VERSION

FROM ${NODE_VERSION}

WORKDIR /usr/src/app

COPY docker.sh /usr/src/app/docker.sh

RUN chmod +x /usr/src/app/docker.sh

COPY package*.json ./

RUN npm ci

COPY . .


RUN npm install -g ts-node

EXPOSE ${PORT}
