version: "3.9"

name: ${APP_CONATINER_NAME}-container-scale
services:
  node-server:
    environment:
      - NODE_ENV=dev
      - PORT=${PORT}
      - APP_NAME=${APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile.scale
    volumes:
      - /usr/src/app
    command: npx ts-node ./src/server.ts

  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - node-server
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
