version: "3.9"

services:
  express-typescript:
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - APP_NAME=${APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - /usr/src/app
    container_name: ${APP_NAME}-Production
    expose:
      - ${PORT}
    ports:
      - "3330:${PORT}"
    command: npx ts-node ./src/server.ts
